# Generated by Django 5.1.6 on 2025-02-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Կատեգորիա', 'verbose_name_plural': 'Կատեգորիաներ'},
        ),
    ]
